<?php

/**
 * @file
 * Contains gain_drupal_tech_test.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function gain_drupal_tech_test_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.gain_drupal_tech_test':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Demo module for tech test. Contains a Recent Articles block and JSON endpoint.') . '</p>';
      return $output;

    default:
  }
}
